const CUSTOM_APP_BAR_HEIGHT = 45.0;
const CUSTOM_TAB_BAR_HEIGHT = 50.0;
const CUSTOM_DIVIDER_HEIGHT = 2.0;
const CUSTOM_APP_BOTTON_BAR_HEIGHT = 85.0;
const CUSTOM_APP_BAR_BOTTOM_MARGIN = 24.0;
const DEFAULT_PADDING = 16.0;
